// SPDX-License-Identifier: BUSL-1.1
pragma solidity ^0.8.34;

/**
 * @title PoolmigoCreate3
 * @notice Minimal CREATE3 factory: deploys any contract to an address that depends only on
 *         (this factory's address, the CALLER, salt) — not on the deployed bytecode, its constructor
 *         args, or the caller's nonce. That is what lets the same contract live at the same address on
 *         every chain where this factory itself sits at the same address AND the same deployer calls it.
 *
 * Mechanism:
 *   0. The effective salt is `keccak256(salt ‖ msg.sender)`: every caller gets its own salt namespace, so a
 *      third party can never occupy the address another deployer intends for its (documented) salts —
 *      calling with the same salt from another address lands elsewhere (salt-squatting guard, K-17).
 *   1. `deploy()` CREATE2-deploys one `Create3Dispatcher` per effective salt. The dispatcher's creation
 *      code is a compile-time constant (no constructor args), so its CREATE2 address is a pure
 *      function of (factory, deployer, salt).
 *   2. `deploy()` then calls the dispatcher with the target's creation code. The dispatcher
 *      CREATEs it — its first CREATE, nonce 1 — so the target lands at
 *      `keccak(rlp([dispatcher, 1]))`, independent of what is being deployed.
 *
 * Operating rules (see script/DeployDeterministic.s.sol + script/deterministic-address-check.sh):
 *   - Deploy this factory ONCE per chain at the SAME address (e.g. as the first transaction of a
 *     dedicated deployer account; or via a canonical deterministic CREATE2 deployer if the chain
 *     has one). Future chains: same drill.
 *   - Cross-chain determinism of a DEPLOYED contract holds only if the SAME deployer address calls
 *     `deploy` on every chain (the project's practice: one dedicated deployer account). A different
 *     deployer (e.g. another key, or a multisig whose address differs per chain) gets a different address.
 *   - Salt discipline: one documented salt per logical contract (`keccak256("poolmigo.vault.v1")`).
 *     Never reuse a salt for different bytecode — the address does not commit to the code it holds.
 *   - An initializer invoked from inside the constructor of a CREATE3-deployed contract runs with
 *     `msg.sender == dispatcher`. `PoolmigoVaultUpgradeable.initialize` takes explicit addresses,
 *     so the atomic deploy+initialize path is safe; keep it that way.
 *   - Do NOT edit this file after a factory is deployed at an address shared across chains: a
 *     different dispatcher creation code (or salt derivation) would predict different addresses.
 */
contract PoolmigoCreate3 {
    error Create3__SaltAlreadyUsed(address dispatcher);
    error Create3__AddressMismatch(address predicted, address actual);

    /// @notice Deploys `creationCode` at {create3Address}(msg.sender, salt). Reverts if the caller already used
    ///         `salt`. The salt is bound to the caller: another address using the same salt cannot collide.
    function deploy(bytes32 salt, bytes memory creationCode) external payable returns (address deployed) {
        bytes32 effectiveSalt = _effectiveSalt(msg.sender, salt);
        address dispatcherAddr = _dispatcherAddress(effectiveSalt);
        if (dispatcherAddr.code.length != 0) revert Create3__SaltAlreadyUsed(dispatcherAddr);
        Create3Dispatcher dispatcher = new Create3Dispatcher{salt: effectiveSalt}();
        deployed = dispatcher.dispatch{value: msg.value}(creationCode);
        address predicted = _create3Address(dispatcherAddr);
        if (deployed != predicted) revert Create3__AddressMismatch(predicted, deployed);
    }

    /// @notice The address `deploy(salt, ...)` lands on when called by `deployer`, for any creation code.
    function create3Address(address deployer, bytes32 salt) public view returns (address) {
        return _create3Address(dispatcherAddress(deployer, salt));
    }

    /// @notice The intermediary dispatcher's CREATE2 address for (`deployer`, `salt`).
    function dispatcherAddress(address deployer, bytes32 salt) public view returns (address) {
        return _dispatcherAddress(_effectiveSalt(deployer, salt));
    }

    /// @dev keccak256(salt ‖ deployer) — 52 packed bytes.
    function _effectiveSalt(address deployer, bytes32 salt) private pure returns (bytes32) {
        return keccak256(abi.encodePacked(salt, deployer));
    }

    function _dispatcherAddress(bytes32 effectiveSalt) private view returns (address) {
        return address(
            uint160(
                uint256(
                    keccak256(
                        abi.encodePacked(
                            bytes1(0xff), address(this), effectiveSalt, keccak256(type(Create3Dispatcher).creationCode)
                        )
                    )
                )
            )
        );
    }

    function _create3Address(address dispatcher) private pure returns (address) {
        return
            address(uint160(uint256(keccak256(abi.encodePacked(bytes1(0xd6), bytes1(0x94), dispatcher, bytes1(0x01))))));
    }
}

/**
 * @dev Implementation detail of {PoolmigoCreate3}: created per salt via CREATE2, then called once
 *      with the target's creation code. Its first CREATE uses nonce 1 — the fixed point CREATE3
 *      relies on. Not intended for direct use.
 */
contract Create3Dispatcher {
    error Create3Dispatcher__Unauthorized();
    error Create3Dispatcher__CreateFailed();

    address public immutable factory;

    constructor() {
        factory = msg.sender;
    }

    /// @dev Bubbles the target constructor's revert data on failure.
    ///      NOTE: CREATE reads init code from *memory* — a calldata pointer would be silently
    ///      reinterpreted as a memory offset (deploying an empty contract). Hence the copy.
    function dispatch(bytes calldata creationCode) external payable returns (address deployed) {
        if (msg.sender != factory) revert Create3Dispatcher__Unauthorized();
        bytes memory code = creationCode;
        assembly ("memory-safe") {
            deployed := create(callvalue(), add(code, 0x20), mload(code))
        }
        if (deployed == address(0)) {
            assembly {
                returndatacopy(0, 0, returndatasize())
                revert(0, returndatasize())
            }
        }
    }
}
